{% set name = "evdev" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evdev-{{ version }}.tar.gz
  sha256: dc640a064cb1c9fe1f8b970dc2039945a2a275d7b7ee62284bf427238abe45ee

build:
  skip: true  # [not linux]
  # C_INCLUDE_PATH is manually parsed by setup.py, required to be set to the Linux kernel header directory
  script: C_INCLUDE_PATH=${CONDA_BUILD_SYSROOT}/usr/include {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=61.0
  run:
    - python

test:
  imports:
    - evdev
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gvalkov/python-evdev
  summary: Bindings to the Linux input handling subsystem
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://python-evdev.readthedocs.io

extra:
  recipe-maintainers:
    - ehfd
    - gvalkov
