{% set name = "evdev" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/evdev-{{ version }}.tar.gz
  sha256: 442fb3f4c8dfc9e61e901133c356220c02d663eca8f34722e0cecdd637eba504

build:
  skip: true  # [not linux or py<311]
  # C_INCLUDE_PATH is manually parsed by setup.py, required to be set to the Linux kernel header directory
  script: C_INCLUDE_PATH=${CONDA_BUILD_SYSROOT}/usr/include {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=77.0
  run:
    - python

test:
  imports:
    - evdev
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gvalkov/python-evdev
  summary: Bindings to the Linux input handling subsystem
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://python-evdev.readthedocs.io

extra:
  recipe-maintainers:
    - ehfd
    - gvalkov
