{% set name = "evdev" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evdev-{{ version }}.tar.gz
  sha256: 45598eee1ae3876a3122ca1dc0ec8049c01931672d12478b5c610afc24e47d75

build:
  skip: true  # [not linux]
  # C_INCLUDE_PATH is manually parsed by setup.py, required to be set to the Linux kernel header directory
  script: C_INCLUDE_PATH=${CONDA_BUILD_SYSROOT}/usr/include {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=61.0
    - pip
  run:
    - python

test:
  imports:
    - evdev
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gvalkov/python-evdev
  summary: Bindings to the Linux input handling subsystem
  doc_url: https://python-evdev.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gvalkov
    - ehfd
